# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b45fc0ab879e7ccf63d409f7050de21a916526ba8adf990a98cc30bc82ad407e8a057580a2b27c6b8a4feee1c03712ff01d50e294a9d2106b5566c21f94d3ee3

test:
  secret_key_base: 0a53672407b357d60c9f23fd27dacb7fc082626d8986f37cfbd33a5ae41c337bd0d78b8f911d60647d4ddf394c1c055752a3bc3a30b6fe1dda68624bc8d282e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
